[package]
name = "thermal-insulation-app"
version = "0.1.0"
description = "Теплоизоляционные материалы"
authors = ["CoolerMasterVC"]
license = "MIT"
edition = "2021"

[[bin]]
name = "thermal-insulation-app"
path = "src/main.rs"

[dependencies]
tauri = { version = "1.0", features = [ "http-request"] }

[build-dependencies]
tauri-build = { version = "1.0", features = [] }
